name: Run Tests with Robot Framework

on:
  workflow_dispatch:
    inputs:
        test_option:
            description: 'Run tests'
            required: true
            type: choice
            options:
                - "test_index.robot"
                - "test_api.robot"

env:
    python-version: '3.11.1'
    chromedriver-version: '134.0.6998.88'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install robotframework
        pip install robotframework-seleniumlibrary
        pip install robotframework-requests
        pip install PyYAML

    - name: Set up ChromeDriver
      uses: nanasess/setup-chromedriver@v2
      with:
        chromedriver-version: ${{ env.chromedriver-version }}

    - name: Run Robot Framework tests
      run: |
        robot --outputdir results testcases/${{ github.event.inputs.test_option }}

    # - name: Upload test results
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: robot-test-results
    #     path: results/

    - name: Upload test results
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: robot-test-results-success
        path: results/
  
    - name: Upload log failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: log-failure
        path: results/