name: Run Tests with Robot Framework

on:
  workflow_dispatch:
    inputs:
        test_option:
            description: 'Run tests'
            required: true
            type: choice
            options:
                - "test_webUI.robot"
                - "test_api.robot"
                - "test_all_step.robot"

env:
    python-version: '3.11.1'
    chromedriver-version: '134.0.6998.88'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install robotframework
        pip install robotframework-seleniumlibrary
        pip install robotframework-requests
        pip install PyYAML

    - name: Set up ChromeDriver
      uses: nanasess/setup-chromedriver@v2
      with:
        chromedriver-version: ${{ env.chromedriver-version }}

    - name: Robot run test option
      if: ${{ github.event.inputs.test_option }} != 'test_all_step.robot'
      run: |
        robot --outputdir results testcases/${{ github.event.inputs.test_option }}

    - name: Robot run all test steps
      if: ${{ github.event.inputs.test_option }} == 'test_all_step.robot'
      run: |
        robot --outputdir results testcases

    - name: Upload test results
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.inputs.test_option }}-results
        path: results/
  
    - name: Upload log failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.inputs.test_option }}-log-failure
        path: results/